"""Pull the two typefaces into the build, so the demo makes no network calls.

The three pages used to link a stylesheet from fonts.googleapis.com. Measured, that was three
requests and about 63 KB on every load - which quietly falsified the property the whole bake
exists to protect. `CLAUDE.md` states it as a rule and the README carries it as a badge.

Run this again only if the typefaces change:

    .venv/Scripts/python scripts/fetch_fonts.py

It writes `web/public/fonts/*.woff2` and `web/public/fonts.css`, which the three HTML entry
points link with a relative path.

Latin and latin-ext only. Google also serves cyrillic and vietnamese subsets of IBM Plex Mono
and a vietnamese subset of Chivo; nothing on any of the three pages uses those glyphs, and the
`unicode-range` on each face means a browser only downloads a subset it actually needs anyway.
"""

from __future__ import annotations

import re
from pathlib import Path

import requests

# Google serves woff2 only to a browser that says it can take it. Asking as Python gets ttf,
# which is four times the size.
BROWSER = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0 Safari/537.36"
    )
}

SOURCE = (
    "https://fonts.googleapis.com/css2"
    "?family=Chivo:wght@400;500;700;900"
    "&family=IBM+Plex+Mono:wght@400;500"
    "&display=swap"
)

KEEP_SUBSETS = {"latin", "latin-ext"}

ROOT = Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "web" / "public" / "fonts"

HEADER = """/*
 * The two typefaces, served from this build.
 *
 * They used to be linked from fonts.googleapis.com, which made three network requests on every
 * page load - about 63 KB - and quietly falsified the one property the whole bake exists to
 * protect: the README badge says "network calls at demo time: 0" and CLAUDE.md states it as a
 * rule. With a dead venue network the pages still worked, because `display=swap` falls back,
 * but the type was not the type the console was designed in, and anyone with devtools open
 * could see the badge was wrong.
 *
 * Generated by scripts/fetch_fonts.py. Latin and latin-ext only: the cyrillic and vietnamese
 * subsets Google also serves are glyphs nothing on any of the three pages uses.
 */

"""


def main() -> None:
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    css = requests.get(SOURCE, headers=BROWSER, timeout=60).text

    faces = re.findall(r"/\*\s*([\w\[\]-]+)\s*\*/\s*@font-face\s*\{(.*?)\}", css, re.S)
    rules: list[str] = []
    total = 0

    for subset, body in faces:
        if subset not in KEEP_SUBSETS:
            continue
        family = re.search(r"font-family: '([^']+)'", body).group(1)
        weight = re.search(r"font-weight: (\d+);", body).group(1)
        url = re.search(r"url\((https://[^)]+\.woff2)\)", body).group(1)
        unicode_range = re.search(r"unicode-range: ([^;]+);", body).group(1)

        name = f"{family.lower().replace(' ', '-')}-{weight}-{subset}.woff2"
        data = requests.get(url, headers=BROWSER, timeout=60).content
        (FONT_DIR / name).write_bytes(data)
        total += len(data)

        rules.append(
            f"/* {subset} */\n"
            f"@font-face {{\n"
            f"  font-family: '{family}';\n"
            f"  font-style: normal;\n"
            f"  font-weight: {weight};\n"
            f"  font-display: swap;\n"
            f"  src: url('./fonts/{name}') format('woff2');\n"
            f"  unicode-range: {unicode_range};\n"
            f"}}"
        )
        print(f"  {name:34s} {len(data):>7,} bytes")

    (FONT_DIR.parent / "fonts.css").write_text(HEADER + "\n\n".join(rules) + "\n", encoding="utf-8")
    print(f"\n{len(rules)} faces, {total:,} bytes -> {FONT_DIR}")


if __name__ == "__main__":
    main()
